"""empty message

Revision ID: 122fa9b7cf5a
Revises: 8b8e74e365b9
Create Date: 2024-08-27 09:22:48.691230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122fa9b7cf5a'
down_revision = '8b8e74e365b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=30), nullable=True),
    sa.Column('avatar', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('Operators')
    # ### end Alembic commands ###
