"""empty message

Revision ID: 1a25b3121f9d
Revises: e39124b7d180
Create Date: 2024-08-27 14:50:56.134102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a25b3121f9d'
down_revision = 'e39124b7d180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Application_Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Application_Settings')
    # ### end Alembic commands ###
