"""empty message

Revision ID: a6b411de1769
Revises: 122fa9b7cf5a
Create Date: 2024-08-27 13:23:25.218280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b411de1769'
down_revision = '122fa9b7cf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Visited_Pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Visited_Pages')
    # ### end Alembic commands ###
