"""empty message

Revision ID: bf1b3bb2b442
Revises: a6b411de1769
Create Date: 2024-08-27 13:37:47.684787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1b3bb2b442'
down_revision = 'a6b411de1769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=35), nullable=True),
    sa.Column('user_id', sa.String(length=35), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=35), nullable=True),
    sa.Column('ip', sa.String(length=35), nullable=True),
    sa.Column('location', sa.String(length=35), nullable=True),
    sa.Column('browser', sa.String(length=35), nullable=True),
    sa.Column('os', sa.String(length=35), nullable=True),
    sa.Column('is_banned', sa.String(length=35), nullable=True),
    sa.Column('last_url', sa.String(length=35), nullable=True),
    sa.Column('last_visit', sa.String(length=35), nullable=True),
    sa.Column('first_visit', sa.String(length=35), nullable=True),
    sa.Column('page_view', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
