"""empty message

Revision ID: e39124b7d180
Revises: bf1b3bb2b442
Create Date: 2024-08-27 14:31:03.783094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39124b7d180'
down_revision = 'bf1b3bb2b442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=35), nullable=True),
    sa.Column('user_id', sa.String(length=35), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('chat_status', sa.String(length=35), nullable=True),
    sa.Column('current_owner', sa.String(length=250), nullable=True),
    sa.Column('all_operators', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=35), nullable=True),
    sa.Column('sender', sa.String(length=35), nullable=True),
    sa.Column('date', sa.String(length=35), nullable=True),
    sa.Column('content', sa.String(length=35), nullable=True),
    sa.Column('message_type', sa.String(length=35), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('reply_to', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=35), nullable=True),
    sa.Column('user_id', sa.String(length=35), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=35), nullable=True),
    sa.Column('ip', sa.String(length=35), nullable=True),
    sa.Column('location', sa.String(length=35), nullable=True),
    sa.Column('browser', sa.String(length=35), nullable=True),
    sa.Column('os', sa.String(length=35), nullable=True),
    sa.Column('is_banned', sa.String(length=35), nullable=True),
    sa.Column('last_url', sa.String(length=35), nullable=True),
    sa.Column('last_visit', sa.String(length=35), nullable=True),
    sa.Column('first_visit', sa.String(length=35), nullable=True),
    sa.Column('page_view', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=35), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=35), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=250), nullable=True),
    sa.Column('name', sa.VARCHAR(length=25), nullable=True),
    sa.Column('email', sa.VARCHAR(length=35), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=35), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=35), nullable=True),
    sa.Column('location', sa.VARCHAR(length=35), nullable=True),
    sa.Column('browser', sa.VARCHAR(length=35), nullable=True),
    sa.Column('os', sa.VARCHAR(length=35), nullable=True),
    sa.Column('is_banned', sa.VARCHAR(length=35), nullable=True),
    sa.Column('last_url', sa.VARCHAR(length=35), nullable=True),
    sa.Column('last_visit', sa.VARCHAR(length=35), nullable=True),
    sa.Column('first_visit', sa.VARCHAR(length=35), nullable=True),
    sa.Column('page_view', sa.VARCHAR(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Users')
    op.drop_table('Messages')
    op.drop_table('Chats')
    # ### end Alembic commands ###
